name: Publish docs

on:
  push:
    branches:
      - main
      - v1.1

jobs:
  public_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node.js setup
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Yarn install
      run: |
        yarn install

    - name: Build docs
      run: |
        yarn docs build

    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packages/docs/build
        user_name: ${{ github.actor }}
        user_email: ${{ github.actor }}@users.noreply.github.com
